#!/bin/bash

if [ ! -f data.json ]; then
  echo "data.json not found."
  exit 1
fi


name=Pickachu
type=$(jq -r '(.types[0].type.name)' data.json | sed 's/electric/Electric/')
formatted_weight=$(jq -r '.weight' data.json | awk '{printf "%.1f", $1/10}') 
formatted_height=$(jq -r '.height' data.json | awk '{printf "%.1f", $1/10}')



echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."